name: Main

on:
  push:
    branches:
      - main
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show secrets
        uses: actions/github-script@v6
        id: tokens
        with:
          script: |
            console.log(">>>>> GITHUB_TOKEN": ${{ secrets.GITHUB_TOKEN }});
            console.log(">>>>> NPM_TOKEN": ${{ secrets.NPM_TOKEN }});

    # - name: Semantic Release
    #   uses: cycjimmy/semantic-release-action@v3
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
