name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup access to qlik npm registry
        shell: bash
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "//npm.pkg.github.com/:always-auth=true" >> ~/.npmrc
          echo "@qlik-oss:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          cat ~/.npmrc

      - name: Install dependencies
        shell: bash
        run: yarn install --immutable

      - name: Build
        run: yarn build:prod

      - name: Publish
        run: |
          # make sure we have .d.ts files in our package
          DTS=`ls ./dist/** | grep d.ts | wc -l`
          echo "# of *.d.ts files is $DTS"
          if [[ $DTS -eq 0 ]]; then
            echo "Missing *.d.ts files"
            exit 1
          fi
          yarn publish ./dist

      # - name: Semantic Release
      #   id: semantic
      #   uses: cycjimmy/semantic-release-action@v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     branches: main

      # - name: Check Release Outputs
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   run: |
      #     echo ${{ steps.semantic.outputs.new_release_version }}
      #     echo ${{ steps.semantic.outputs.new_release_major_version }}
      #     echo ${{ steps.semantic.outputs.new_release_minor_version }}
      #     echo ${{ steps.semantic.outputs.new_release_patch_version }}
